spring.datasource.url=${DATABASE_NAME:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
spring.datasource.username=${DATABASE_USERNAME:postgres.baqrkprkqakmwnewugwh}
spring.datasource.password=${DATABASE_PASSWORD:WLaGpYKaftZ5ZkFc}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.address=0.0.0.0
server.port=${PORT:8080}
sage-math.url=${SAGE_MATH_URL:http://localhost:8000}
sage-math.connect-timeout=${SAGE_MATH_CONNECT_TIMEOUT:2s}
sage-math.read-timeout=${SAGE_MATH_READ_TIMEOUT:30s}
